name: im_model_gen
version: 1.5.0
description: Annotation builder for immutable model to generate of `copyWith` and == (equal) operator..
homepage: https://github.com/llfbandit/immutable_model/tree/master/im_model_gen

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: '>=7.4.0 <9.0.0'  # https://pub.dev/packages/analyzer
  build: ^4.0.0               # https://pub.dev/packages/build
  im_model: ^1.2.1
  meta: ^1.15.0               # https://pub.dev/packages/meta
  source_gen: ^4.0.1          # https://pub.dev/packages/source_gen

dev_dependencies:
  lints: ^6.0.0               # https://pub.dev/packages/lints
  build_runner: ^2.7.2        # https://pub.dev/packages/build_runner
  test: ^1.19.4               # https://pub.dev/packages/test
  source_gen_test: ^1.3.2     # https://pub.dev/packages/source_gen_test
