name: im_model_gen
version: 1.6.0
description: Annotation builder for immutable model to generate of `copyWith` and == (equal) operator..
homepage: https://github.com/llfbandit/immutable_model/tree/master/im_model_gen

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  analyzer: '>=8.1.1 <10.0.0'  # https://pub.dev/packages/analyzer
  build: ^4.0.3               # https://pub.dev/packages/build
  im_model: ^1.3.0
  meta: ^1.15.0               # https://pub.dev/packages/meta
  source_gen: ^4.0.1          # https://pub.dev/packages/source_gen

dev_dependencies:
  lints: ^6.0.0               # https://pub.dev/packages/lints
  build_runner: ^2.10.4        # https://pub.dev/packages/build_runner
  test: ^1.19.4               # https://pub.dev/packages/test
  source_gen_test: ^1.3.3     # https://pub.dev/packages/source_gen_test
